version: '3.1'

volumes:
  node_modules:
  meilisearch:

services:
  web:
    build:
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./:/app
      - /app/.pnpm-store/
      - node_modules:/app/node_modules

    ports:
      - 8080:8080
    command: sh -c "pnpm install && pnpm run build && http-server dist"

  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      MEILI_MASTER_KEY: quantiPass1234
    ports:
      - 7700:7700
    volumes:
      - meilisearch:/meili_data

  ruby:
    build:
      dockerfile: ./Dockerfile-ruby
    volumes:
      - ./ruby:/home
